# Generated by Django 4.1.1 on 2022-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=256)),
                ('categoria', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('director_tecnico', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estadio', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('fecha_de_nacimento', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=256)),
                ('equipo', models.CharField(max_length=256)),
            ],
        ),
    ]
