# Generated by Django 4.1.1 on 2022-09-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='fecha_de_nacimento',
            field=models.DateField(),
        ),
    ]
